# Generated by Django 5.2.1 on 2025-05-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='carnet',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet'),
        ),
        migrations.AddField(
            model_name='registro',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='grado',
            field=models.CharField(choices=[('grado1', 'Ninguno'), ('grado2', 'Noveno Grado'), ('grado3', 'Bachiller'), ('grado4', 'Superior')], default='grado1', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='movil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Movil'),
        ),
        migrations.AddField(
            model_name='registro',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(choices=[('ocupacion1', 'Desocupado'), ('ocupacion2', 'Ama de Casa'), ('ocupacion3', 'Trabajador Estatal'), ('ocupacion4', 'Trabajador por Cuenta Propia')], default='ocupacion1', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='provincia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Carnet'),
        ),
        migrations.AddField(
            model_name='registro',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
    ]
