# Generated by Django 5.2.1 on 2025-05-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registro_carnet_registro_correo_registro_grado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='correo',
        ),
        migrations.AlterField(
            model_name='registro',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(default='plantilla.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='movil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
    ]
