# Generated by Django 5.2.1 on 2025-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_registro_correo_alter_registro_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(default='plantilla.jpg', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]
