# Generated by Django 5.2.1 on 2025-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_registro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(default='default/plantilla.jpg', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]
