# Generated by Django 5.2.1 on 2025-07-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_ocupacion_choices'),
        ('accounts', '0007_alter_registro_image'),
    ]

    operations = [
    ]
