# Generated by Django 5.2.1 on 2025-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20250723_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='foto_carnet',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/carnets/', verbose_name='Foto del Carnet'),
        ),
        migrations.AddField(
            model_name='registro',
            name='foto_titulo',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/titulos/', verbose_name='Foto del Título'),
        ),
    ]
