# Generated by Django 5.2.7 on 2025-10-29 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAcademicoArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Curso Académico')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('archivado', models.BooleanField(default=True, verbose_name='Archivado')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
            ],
            options={
                'verbose_name': 'Curso Académico Archivado',
                'verbose_name_plural': 'Cursos Académicos Archivados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CursoArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('name', models.CharField(max_length=90, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('area', models.CharField(choices=[('idiomas', 'Idiomas'), ('humanidades', 'Humanidades'), ('computacion', 'Computación'), ('diseno', 'Diseño'), ('adolescentes', 'Adolescentes'), ('teologia', 'Teología')], default='idiomas', max_length=20, verbose_name='Área')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado'), ('grado', 'Grado'), ('taller', 'Taller')], default='curso', max_length=20, verbose_name='Tipo')),
                ('teacher_id_original', models.IntegerField(verbose_name='ID Original del Profesor en MariaDB')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='Nombre del Profesor')),
                ('class_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Clases')),
                ('status', models.CharField(choices=[('I', 'En etapa de inscripción'), ('IT', 'Plazo de Inscripción Terminado'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=15, verbose_name='Estado')),
                ('enrollment_deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite de inscripción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del curso')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('curso_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.cursoacademicoarchivado', verbose_name='Curso Académico Archivado')),
                ('teacher_actual', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Profesores'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesor Actual Vinculado')),
            ],
            options={
                'verbose_name': 'Curso Archivado',
                'verbose_name_plural': 'Cursos Archivados',
                'ordering': ['-curso_academico__fecha_creacion', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaArchivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('fecha_matricula', models.DateField(verbose_name='Fecha de Matrícula')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Reprobado'), ('L', 'Licencia'), ('B', 'Baja')], default='P', max_length=1, verbose_name='Estado')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.cursoarchivado', verbose_name='Curso Archivado')),
            ],
            options={
                'verbose_name': 'Matrícula Archivada',
                'verbose_name_plural': 'Matrículas Archivadas',
                'ordering': ['-fecha_matricula'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionArchivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.cursoarchivado', verbose_name='Curso Archivado')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_archivadas', to='datos_archivados.matriculaarchivada', verbose_name='Matrícula Archivada')),
            ],
            options={
                'verbose_name': 'Calificación Archivada',
                'verbose_name_plural': 'Calificaciones Archivadas',
            },
        ),
        migrations.CreateModel(
            name='MigracionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('error', 'Error')], default='iniciada', max_length=20, verbose_name='Estado')),
                ('usuarios_migrados', models.IntegerField(default=0, verbose_name='Usuarios Migrados')),
                ('cursos_academicos_migrados', models.IntegerField(default=0, verbose_name='Cursos Académicos Migrados')),
                ('cursos_migrados', models.IntegerField(default=0, verbose_name='Cursos Migrados')),
                ('matriculas_migradas', models.IntegerField(default=0, verbose_name='Matrículas Migradas')),
                ('calificaciones_migradas', models.IntegerField(default=0, verbose_name='Calificaciones Migradas')),
                ('notas_migradas', models.IntegerField(default=0, verbose_name='Notas Migradas')),
                ('asistencias_migradas', models.IntegerField(default=0, verbose_name='Asistencias Migradas')),
                ('errores', models.TextField(blank=True, verbose_name='Errores encontrados')),
                ('host_origen', models.CharField(max_length=255, verbose_name='Host de origen')),
                ('base_datos_origen', models.CharField(max_length=255, verbose_name='Base de datos de origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ejecutó la migración')),
            ],
            options={
                'verbose_name': 'Log de Migración',
                'verbose_name_plural': 'Logs de Migración',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NotaIndividualArchivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor de la Nota')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_archivadas', to='datos_archivados.calificacionarchivada', verbose_name='Calificación Archivada')),
            ],
            options={
                'verbose_name': 'Nota Individual Archivada',
                'verbose_name_plural': 'Notas Individuales Archivadas',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('username', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_joined', models.DateTimeField(verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nacionalidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nacionalidad')),
                ('carnet', models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio')),
                ('provincia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Provincia')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('movil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Móvil')),
                ('grado', models.CharField(choices=[('grado1', 'Ninguno'), ('grado2', 'Noveno Grado'), ('grado3', 'Bachiller'), ('grado4', 'Superior')], default='grado1', max_length=50, verbose_name='Grado Académico')),
                ('ocupacion', models.CharField(choices=[('ocupacion1', 'Desocupado'), ('ocupacion2', 'Estudiante'), ('ocupacion3', 'Ama de Casa'), ('ocupacion4', 'Trabajador Estatal'), ('ocupacion5', 'Trabajador por Cuenta Propia')], default='ocupacion1', max_length=100, verbose_name='Ocupación')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título')),
                ('grupo', models.CharField(blank=True, max_length=50, verbose_name='Grupo')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('usuario_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_archivados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual Vinculado')),
            ],
            options={
                'verbose_name': 'Usuario Archivado',
                'verbose_name_plural': 'Usuarios Archivados',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AddField(
            model_name='matriculaarchivada',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_archivadas', to='datos_archivados.usuarioarchivado', verbose_name='Estudiante Archivado'),
        ),
        migrations.AddField(
            model_name='calificacionarchivada',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.usuarioarchivado', verbose_name='Estudiante Archivado'),
        ),
        migrations.CreateModel(
            name='AsistenciaArchivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('presente', models.BooleanField(blank=True, default=False, null=True, verbose_name='Asistió')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.cursoarchivado', verbose_name='Curso Archivado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_archivadas', to='datos_archivados.usuarioarchivado', verbose_name='Estudiante Archivado')),
            ],
            options={
                'verbose_name': 'Asistencia Archivada',
                'verbose_name_plural': 'Asistencias Archivadas',
                'ordering': ['-date'],
            },
        ),
    ]
