# Generated by Django 5.2.7 on 2025-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoArchivadoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_origen', models.CharField(max_length=100, verbose_name='Tabla de Origen')),
                ('id_original', models.IntegerField(verbose_name='ID Original en MariaDB')),
                ('datos_originales', models.JSONField(verbose_name='Datos Originales')),
                ('estructura_tabla', models.JSONField(blank=True, null=True, verbose_name='Estructura de la Tabla')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('nombre_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Registro')),
                ('tipo_registro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Registro')),
            ],
            options={
                'verbose_name': 'Dato Archivado Dinámico',
                'verbose_name_plural': 'Datos Archivados Dinámicos',
                'ordering': ['-fecha_migracion'],
                'indexes': [models.Index(fields=['tabla_origen', 'id_original'], name='datos_archi_tabla_o_10d2ce_idx'), models.Index(fields=['fecha_migracion'], name='datos_archi_fecha_m_03de48_idx'), models.Index(fields=['tipo_registro'], name='datos_archi_tipo_re_25e18c_idx')],
                'unique_together': {('tabla_origen', 'id_original')},
            },
        ),
    ]
