# Generated by Django 5.2.7 on 2025-11-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0002_datoarchivadodinamico'),
    ]

    operations = [
        migrations.AddField(
            model_name='migracionlog',
            name='tablas_con_datos',
            field=models.IntegerField(default=0, verbose_name='Tablas con Datos'),
        ),
        migrations.AddField(
            model_name='migracionlog',
            name='tablas_inspeccionadas',
            field=models.IntegerField(default=0, verbose_name='Tablas Inspeccionadas'),
        ),
        migrations.AddField(
            model_name='migracionlog',
            name='tablas_vacias',
            field=models.IntegerField(default=0, verbose_name='Tablas Vacías'),
        ),
        migrations.AlterField(
            model_name='migracionlog',
            name='usuarios_migrados',
            field=models.IntegerField(default=0, verbose_name='Registros Migrados'),
        ),
    ]
