# Generated by Django 5.2.7 on 2025-11-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0003_migracionlog_tablas_con_datos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código de Verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('dato_archivado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.datoarchivadodinamico', verbose_name='Dato Archivado')),
                ('usuario_archivado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_archivados.usuarioarchivado', verbose_name='Usuario Archivado')),
            ],
            options={
                'verbose_name': 'Código de Verificación para Reclamación',
                'verbose_name_plural': 'Códigos de Verificación para Reclamación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
