# Generated by Django 5.2.1 on 2025-06-22 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('archivado', models.BooleanField(default=False, verbose_name='Archivado')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/plantilla.jpg', upload_to='imagenes/', verbose_name='Imagen de curso')),
                ('name', models.CharField(max_length=90, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('class_quantity', models.PositiveIntegerField(default=0, verbose_name='Catidad de Clases')),
                ('status', models.CharField(choices=[('I', 'En etapa de inscripcion'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=15, verbose_name='Estado')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Profesores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(blank=True, default=False, null=True, verbose_name='Asistió')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('nota_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('nota_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('nota_4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 4')),
                ('nota_5', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 5')),
                ('nota_6', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 6')),
                ('average', models.DecimalField(blank=True, decimal_places=1, editable='False', max_digits=3, null=True, verbose_name='Promedio')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cursoacademico', verbose_name='Curso Académico')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('course', 'student', 'curso_academico')},
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('fecha_matricula', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Reprobado'), ('L', 'Licencia'), ('B', 'Baja')], default='P', max_length=1, verbose_name='Estado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cursoacademico', verbose_name='Curso Académico')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'unique_together': {('student', 'course', 'curso_academico')},
            },
        ),
    ]
