# Generated by Django 5.2.1 on 2025-06-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='matricula',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='principal.matriculas', verbose_name='Matrícula'),
        ),
    ]
