# Generated by Django 5.2.1 on 2025-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_calificaciones_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
