# Generated by Django 5.2.1 on 2025-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_asistencia_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('I', 'En etapa de inscripción'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=15, verbose_name='Estado'),
        ),
    ]
