# Generated by Django 5.2.1 on 2025-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de inscripción'),
        ),
    ]
