# Generated by Django 5.2.1 on 2025-07-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del curso'),
        ),
    ]
