# Generated by Django 5.2.1 on 2025-07-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_curso_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_1',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_2',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_3',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_4',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_5',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota_6',
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True, verbose_name='Promedio'),
        ),
        migrations.CreateModel(
            name='NotaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor de la Nota')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='principal.calificaciones', verbose_name='Calificación')),
            ],
            options={
                'verbose_name': 'Nota Individual',
                'verbose_name_plural': 'Notas Individuales',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
