# Generated by Django 5.2.1 on 2025-07-19 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_curso_curso_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='class_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Clases'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('student', 'date', 'course')},
        ),
    ]
