# Generated by Django 5.2.1 on 2025-07-19 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_curso_class_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del formulario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_aplicacion', to='principal.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Formulario de Aplicación',
                'verbose_name_plural': 'Formularios de Aplicación',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la pregunta')),
                ('tipo', models.CharField(choices=[('seleccion_unica', 'Selección Única'), ('seleccion_multiple', 'Selección Múltiple')], default='seleccion_unica', max_length=20, verbose_name='Tipo de pregunta')),
                ('requerida', models.BooleanField(default=True, verbose_name='Requerida')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='principal.formularioaplicacion', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Pregunta de Formulario',
                'verbose_name_plural': 'Preguntas de Formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='principal.preguntaformulario', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='principal.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_inscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='principal.formularioaplicacion', verbose_name='Formulario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Inscripción',
                'verbose_name_plural': 'Solicitudes de Inscripción',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones_seleccionadas', models.ManyToManyField(related_name='respuestas', to='principal.opcionrespuesta', verbose_name='Opciones seleccionadas')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='principal.preguntaformulario', verbose_name='Pregunta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='principal.solicitudinscripcion', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
                'unique_together': {('solicitud', 'pregunta')},
            },
        ),
    ]
