# Generated by Django 5.2.1 on 2025-07-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_opcionrespuesta_texto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularioaplicacion',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': '📋 Formulario de Aplicación', 'verbose_name_plural': '📋 Formularios de Aplicación'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'ordering': ['orden'], 'verbose_name': '✅ Opción de Respuesta', 'verbose_name_plural': '✅ Opciones de Respuesta'},
        ),
        migrations.AlterModelOptions(
            name='preguntaformulario',
            options={'ordering': ['orden'], 'verbose_name': '❓ Pregunta de Formulario', 'verbose_name_plural': '❓ Preguntas de Formulario'},
        ),
        migrations.AlterModelOptions(
            name='respuestaestudiante',
            options={'verbose_name': '💬 Respuesta de Estudiante', 'verbose_name_plural': '💬 Respuestas de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudinscripcion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': '📝 Solicitud de Inscripción', 'verbose_name_plural': '📝 Solicitudes de Inscripción'},
        ),
    ]
