# Generated by Django 5.2.1 on 2025-07-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_formularioaplicacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.CharField(choices=[('idiomas', 'Idiomas'), ('humanidades', 'Humanidades'), ('computacion', 'Computación'), ('diseno', 'Diseño'), ('adolescentes', 'Adolescentes'), ('teologia', 'Teología')], default='idiomas', max_length=20, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('diplomado', 'Diplomado'), ('grado', 'Grado'), ('taller', 'Taller')], default='curso', max_length=20, verbose_name='Tipo'),
        ),
    ]
