# Generated by Django 5.2.7 on 2025-10-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_curso_area_curso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaformulario',
            name='tipo',
            field=models.CharField(choices=[('seleccion_multiple', 'Selección Múltiple'), ('seleccion_unica', 'Selección Única'), ('escritura_libre', 'Escritura Libre')], default='seleccion_multiple', max_length=20, verbose_name='Tipo de pregunta'),
        ),
    ]
